### ISSUE TITLE
Add metadata tag to staging to prevent search engine crawling

### ISSUE THREAD

**Issue by rmcilwain6** [VikeLabs/vikelabs.ca#11]
### User Story

As a developer I would like to add a metadata tag tag to the staging branch so that I can prevent it from being indexed by search engines.

### Details

This link below explains the importance of this ticket.
>https://developers.google.com/search/docs/advanced/crawling/block-indexing?hl=en&visit_id=637411874217558347-3259896579&rd=1

Goal for this task is to add the following metadata tag to the staging branch.
```
<meta name="robots" content="noindex">
```

### Acceptance Criteria

- [ ] Metadata tag has been implemented correctly

Something to keep in mind is that when we merge staging into the master branch, this will need to be undone whenever that process happens to ensure the production site continues to be indexed.

**Comment by aomi** [comment]
I think there can be build time flags to include/don't include it.
