### ISSUE TITLE
Initial Staging Branch Setup

### ISSUE THREAD

**Issue by rmcilwain6** [VikeLabs/vikelabs.ca#3]
Items to do:
 - [ ] Create GitHub Actions for PR checks [Issue #10](https://github.com/VikeLabs/vikelabs.ca/issues/10)
    - [ ] Lint Check
    - [ ] Formatting/Prettier check
    - [ ] Build check
- [ ] Set the staging branch to have a required status check for the pr_check job [(how-to)](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/about-required-status-checks)
- [x] Tear down existing staging environment to best "blank slate" status
- [x] Port over project management items to this repo
- [ ] Update GitHub documentation
    - [ ] Update README
    - [ ] Update PR template
    - [x] Update Issue template
- [ ] Add noindex metadata header to staging site to prevent search engine crawling

**Comment by ollewis** [comment]
RE: GitHub Actions
- [Starter Workflows/Templates](https://github.com/actions/starter-workflows) - Has some great templates for GitHub workflows
    - [Blank CI template](https://github.com/actions/starter-workflows/blob/main/ci/blank.yml) - Good for anything CI related.
    - [NodeJS CI template](https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml) - Shows how to run npm commands to test installs, deploys, etc.

**Comment by ollewis** [comment]
RE: GitHub Actions
The formatting check is done with "npm format"? If so, does this not modify files? I still need to figure out how to actually run a "check".

**Comment by aomi** [comment]
@ollewis A `npm format` typically runs and modifies code to comply with format settings (probably with prettier). You might not have the required packages in this repo so you'll need to add them. I expect `eslint` and `prettier`.

**Comment by ollewis** [comment]
Little update on the GitHub Actions task: I'm currently working on getting an auto commit set up such that changes made by eslint and prettier are included in the PR. It's failing at the moment since I'm running the check with multiple node versions; the first one to complete succeeds and creates a commit, the other ones will fail. Should be a quick fix for me on another day.

**Comment by rmcilwain6** [comment]
sure, and just let me know which specific check to enable, right now I see there's 4 different ones right now
![image](https://user-images.githubusercontent.com/31049198/99347593-4ed2de80-284c-11eb-9739-e3e0ca882a08.png)

**Comment by ollewis** [comment]
> sure, and just let me know which specific check to enable, right now I see there's 4 different ones right now

@rmcilwain6 Assuming we want to check all node versions we're currently testing I think the first option is the one to enable.
